baseURL: "https://eomjoo.github.io/"
title: "My Awesome Site"
defaultContentLanguage: "ko"

menu:
  main:
    - name: 엄주영
      weight: 100

    - parent: 엄주영
      name: 자기소개
      url: about
      weight: 110

    - parent: 엄주영
      name: 자기소개2
      url: about1
      weight: 120

    - name: Inform
      url: post
      weight: 200

    - parent: Inform
      name: Notifications
      url: notification
      weight: 210

    - parent: Inform
      name: News
      url: news
      weight: 220

    - name: 코딩 교육
      weight: 300

    - parent: 코딩 교육
      name: 자바스크립트
      url: teaching/js
      weight: 310

    - parent: 코딩 교육
      name: 파이썬
      url: teaching/python
      weight: 320

    - name: "취미"
      identifier: "hobby"
      weight: 400

    - name: "basketball"
      url: "/basketball"
      parent: "hobby"
      weight: 410

    - name: "running"
      url: "/running"
      parent: "hobby"
      weight: 420

    - name: "Contact"
      identifier: "contact"
      url: "/contact"
      weight: 500

    - name: "contact"
      url: "/contact"
      parent: "contact"
      weight: 510

    - name: "practice"
      url: "/publication"
      parent: "contact"
      weight: 520
color: emerald
