baseURL: "https://eomjoo.github.io/"
title: "엄주영 Portfolio Site"
defaultContentLanguage: "en"

menu:
  main:
    - name: Owner
      weight: 100

    - parent: Owner
      name: About Me
      url: about
      weight: 110

    - parent: Owner
      name: Interests
      url: about1
      weight: 120

    - name: Information
      url: post
      weight: 200

    - parent: Information
      name: Notifications
      url: notification
      weight: 210

    - parent: Information
      name: News
      url: news
      weight: 220

    - name: Coding Education
      weight: 300

    - parent: Coding Education
      name: JavaScript
      url: teaching/js
      weight: 310

    - parent: Coding Education
      name: Python
      url: teaching/python
      weight: 320

    - parent: Coding Education
      name: Java
      url: teaching/java
      weight: 330

    - name: Hobby
      identifier: "hobby"
      weight: 400

    - name: Basketball
      url: "/basketball"
      parent: "hobby"
      weight: 410

    - name: Running
      url: "/running"
      parent: "hobby"
      weight: 420

    - name: Reading
      url: publication
      parent: "hobby"
      weight: 430

    - name: Meet-up
      weight: 500

    - parent: Meet-up
      name: Location
      url: contact
      weight: 510

    - parent: Meet-up
      name: Study Places
      url: where
      weight: 520

sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"
