baseURL: "https://eomjoo.github.io/"
title: "My Awesome Site"
defaultContentLanguage: "ko"


menu:
  main:

    - name: 엄주영
      weight: 400

    - parent: 엄주영
      name: 자기소개
      url: about
      weight: 410

    - parent: 엄주영
      name: 자기소개2
      url: about1
      weight: 420

    - name: Inform
      url: post
      weight: 600
    - parent: Inform
      name: Notifications
      url: notification
      weight: 610
    - parent: Inform
      name: News
      url: news
      weight: 620
    - parent: Inform
      name: Event
      url: event
      weight: 630


    - name: "취미"
      identifier: "hobby"
      weight: 60

    - name: "Contact"
      url: "/contact"
      weight: 700

    - name: "basketball"
      url: "/basketball"
      parent: "hobby"
      weight: 10

    - name: "running"
      url: "/running"
      parent: "hobby"
      weight: 20



