baseURL: "https://eomjoo.github.io/"
title: "My Awesome Site"
defaultContentLanguage: "ko"


menu:
  main:


    - name: "자기소개"
      identifier: "resume"
      url: "about/"
      weight: 30

    - name: "프로젝트"
      identifier: "project"
      weight: 40

    - name: "공부 목표"
      weight: 50

    - name: "취미"
      identifier: "hobby"
      weight: 60

    - name: "서식지"
      url: "/contact"
      weight: 70

    - name: "basketball"
      url: "/basketball"
      parent: "hobby"
      weight: 10

    - name: "running"
      url: "/running"
      parent: "hobby"
      weight: 20

    - name: "My page"
      parent: "resume"
      url: "about/"
      weight: 11

