baseURL: "https://eomjoo.github.io/"
title: "Eomjoo portpolio Site"
defaultContentLanguage: "ko"

menu:
  main:
    - name: 엄주영
      weight: 100

    - parent: 엄주영
      name: 자기소개
      url: about
      weight: 110

    - parent: 엄주영
      name: 관심분야
      url: about1
      weight: 120

    - name: 정보
      url: post
      weight: 200

    - parent: 정보
      name: 알림
      url: notification
      weight: 210

    - parent: 정보
      name: 뉴스
      url: news
      weight: 220

    - name: 코딩 교육
      weight: 300

    - parent: 코딩 교육
      name: 자바스크립트
      url: teaching/js
      weight: 310

    - parent: 코딩 교육
      name: 파이썬
      url: teaching/python
      weight: 320

    - parent: 코딩 교육
      name: 자바
      url: teaching/java
      weight: 330

    - name: "취미"
      identifier: "hobby"
      weight: 400

    - name: "농구"
      url: "/basketball"
      parent: "hobby"
      weight: 410

    - name: "달리기"
      url: "/running"
      parent: "hobby"
      weight: 420

    - name: "독서"
      url: publication
      parent: "hobby"
      weight: 430

    - name: "Contact"
      identifier: "contact"
      weight: 500

    - name: "contact"
      url: "/contact"
      parent: "contact"
      weight: 510

    - name: "practice"
      url: "/publication"
      parent: "contact"
      weight: 520

    - name: 만남
      weight: 500

    - parent: 만남
      name: 위치
      url: contact
      weight: 510




sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"
