main:
  - name: J0House
    url: /
    weight: 1
    identifier: "j0house"


  - name: Resume
    identifier: resume
    weight: 30

  - name: Project
    identifier: project
    weight: 40

  - name: Will study
    weight: 50

  - name: Hobby
    identifier: hobby
    weight: 60

  - name: Contact
    weight: 70

  - name: basketball
    parent: hobby
    weight: 10

  - name: running
    parent: hobby
    weight: 20

  - name: My page
    parent: resume
    url: about/
    weight: 10




